### ISSUE TITLE
Discussions页面打开错误

### ISSUE THREAD

**Issue by OnionSalt** [zyfworks/AnotherSteamCommunityFix#1]
首先感谢大神的工具！

开启以后profile, activity等页面都可以正常打开，但是游戏的讨论Discussions页面无法打开，会出现如下信息：

Error
Sorry!
An error was encountered while processing your request:

No forum available

Here's a link to the Steam Community home page.

所有游戏讨论页面都这样。。。

**Comment by makazeu** [comment]
这是valve主动的行为，也就是说valve自行屏蔽了国区的讨论区，国内ip无法访问。使用程序的代理模式可破。

**Comment by OnionSalt** [comment]
代理模式要在境外租服务器吗？服务器端要怎么设置呢？

**Comment by makazeu** [comment]
我编译好的二进制程序中，已经预置了代理服务器，可以直接使用，如果你自己编译的话，需要自己配置。代理服务端使用的是gost的kcp功能。
