### ISSUE TITLE
No alert when failed to listen port

### ISSUE THREAD

**Issue by TinkoLiu** [zyfworks/AnotherSteamCommunityFix#2]
When localhost 80 or/and 443 already used by other process (nginx/apache/etc.), still got listen success text on console output.
当本机80/443端口被其它进程占用时仍然提示监听成功

**Comment by makazeu** [comment]
Go语言socket的默认监听会监听ipv4、ipv6的80/443端口，哪怕ipv4被占用了，只要ipv6的监听成功了也不会报错Orz    现在该问题通过强制指定ipv4而解决。感谢反馈
