### ISSUE TITLE
443、80端口被占用，服务器挂卡

### ISSUE THREAD

**Issue by inkss** [zyfworks/AnotherSteamCommunityFix#5]
netstat -anp|grep 443
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      28790/httpd

**Comment by inkss** [comment]
阿帕奇的服务器在监听443，有没有别的办法能访问社区，想着能在服务器上再放一个ASF来着

**Comment by inkss** [comment]
想利用ASF挂卡，但是面临一个访问不了社区的问题，但是你的程序又监听80和443端口，这边服务器网站又在用，ASF应该是连社区的**徽章的页面**的时候才出错的，所有能不能出一种只负责这种行为的模式。

没学过Go语言就很心疼自己，代码看不懂。

**Comment by makazeu** [comment]
ASF挂卡的话其实并不需要该程序，直接修改hosts就好了。

由于这个程序的实现原理所限制，必须得监听80和443端口，除了前面所述的直接改hosts的办法，你也可以把该程序运行在另一台服务器上甚至docker容器中。
